from sqlalchemy import String, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.db.session import SessionLocal
from app.db.transaction import transaction
from app.repositories.base import Repository


class _TestBase(DeclarativeBase):
    pass


class _TestEntity(_TestBase):
    __tablename__ = "repository_test"

    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True,
    )

    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )


class _TestEntityRepository(Repository[_TestEntity]):
    def get(self, entity_id: str) -> _TestEntity | None:
        return self.db.get(_TestEntity, int(entity_id))


def test_repository_base_contract():
    db = SessionLocal()

    try:
        db.execute(
            text(
                """
                CREATE TEMP TABLE repository_test (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL
                )
                """
            )
        )

        entity = _TestEntity(name="repository-test")

        db.add(entity)
        db.commit()
        db.refresh(entity)

        repository = _TestEntityRepository(db)

        result = repository.get(str(entity.id))

        assert result is not None
        assert result.name == "repository-test"

    finally:
        db.rollback()
        db.close()

def test_transaction_commit_and_rollback():
    db = SessionLocal()

    try:
        db.execute(
            text(
                """
                CREATE TEMP TABLE transaction_test (
                    id INTEGER PRIMARY KEY,
                    value TEXT NOT NULL
                )
                """
            )
        )

        with transaction(db):
            db.execute(
                text(
                    "INSERT INTO transaction_test (id, value) "
                    "VALUES (1, 'committed')"
                )
            )

        result = db.execute(
            text(
                "SELECT value FROM transaction_test "
                "WHERE id = 1"
            )
        ).scalar_one()

        assert result == "committed"

        try:
            with transaction(db):
                db.execute(
                    text(
                        "INSERT INTO transaction_test (id, value) "
                        "VALUES (2, 'rolled-back')"
                    )
                )

                raise RuntimeError("force rollback")

        except RuntimeError:
            pass

        result = db.execute(
            text(
                "SELECT COUNT(*) FROM transaction_test "
                "WHERE id = 2"
            )
        ).scalar_one()

        assert result == 0

    finally:
        db.rollback()
        db.close()