"""add document version constraints

Revision ID: 42b10f331d4b
Revises: 53c6f74f42be
Create Date: 2026-08-17 14:03:39.771704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b10f331d4b'
down_revision: Union[str, Sequence[str], None] = '53c6f74f42be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_content_hash', 'document_versions', ['document_id', 'content_hash'])
    op.create_unique_constraint('uq_document_version_number', 'document_versions', ['document_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_version_number', 'document_versions', type_='unique')
    op.drop_constraint('uq_document_content_hash', 'document_versions', type_='unique')
    # ### end Alembic commands ###
