"""add document version parent relationship

Revision ID: 53c6f74f42be
Revises: c6ce8a0bae2c
Create Date: 2026-08-17 13:56:41.693403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c6f74f42be'
down_revision: Union[str, Sequence[str], None] = 'c6ce8a0bae2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('parent_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'document_versions', 'document_versions', ['parent_version_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_column('document_versions', 'parent_version_id')
    # ### end Alembic commands ###
